# Server 配置
server:
  port: 8890
  servlet:
    context-path: /prod/

# MySQL/Redis 数据库配置；生产环境，连接服务器的本地生产数据库(mysql:imghub)
spring:
  datasource:
    password: rain8240
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imghub?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  redis:
    host: localhost