# MyBatis 配置
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: cn.lmsite.imghub.entity
# Spring 配置
spring:
  jpa:
    open-in-view: false
  redis:
    # Redis 数据库索引（默认为0）
    database: 10
    # Redis 服务器连接端口
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password: ''
    timeout: 8000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 0
#  security:
#    user:
#      name:
#      password:
