# MyBatis 配置
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: cn.lmsite.imghub.entity

# Server 配置
server:
  port: 8892
  servlet:
    context-path: /dev/

# MySQL/Redis 数据库配置；本地环境，连接服务器的测试数据库(mysql:imghub_dev)
spring:
  datasource:
    password: rain8240
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.172.232:3306/imghub_dev?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  jpa:
    open-in-view: false
  redis:
    host: 47.99.172.232
    # Redis 数据库索引（默认为0）
    database: 10
    # Redis 服务器连接端口
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password: ''
    timeout: 8000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 0
#  security:
#    user:
#      name:
#      password:
