# Server 配置
server:
  port: 8892
  servlet:
    context-path: /dev/

# MySQL/Redis 数据库配置；本地环境，连接服务器的测试数据库(mysql:imghub_dev)
spring:
  datasource:
    password: rain8240
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.172.232:3306/imghub_dev?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  redis:
    host: 47.99.172.232