mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: cn.lmsite.imghub.entity

server:
  port: 7218
  servlet:
    context-path: /api/

spring:
  jpa:
    open-in-view: false
  datasource:
    password: rain8240
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imghub?useUnicode=true&useSSL=false&characterEncoding=utf8
